#!/usr/bin/env python3
"""
Fast Liquid Leaders intraday reranker.

Uses the baseline file generated by fetch_leaders.py to recompute weekly RS and
rankings, ATR extension, and price/SMA states from current quotes without
redownloading the full historical universe.
"""

import json
import math
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone, timedelta

import yfinance as yf

try:
    from zoneinfo import ZoneInfo
    ET_ZONE = ZoneInfo("America/New_York")
except Exception:
    ET_ZONE = timezone(timedelta(hours=-4))

try:
    import requests
except ImportError:
    requests = None

try:
    from curl_cffi import requests as cffi_requests
    _session = cffi_requests.Session(impersonate="chrome")
    yf.Ticker._session = _session
except ImportError:
    _session = None

from fetch_data import percentrank_inc
from fetch_leaders import (
    INTRADAY_BASELINES_FILE,
    LOOKBACK_W,
    MA_LENGTH_W,
    MAX_HISTORY_DAYS,
    SETUP_COILED_FLAG,
    is_us_market_holiday,
)

LEADERS_FILE = "leaders.json"
HISTORY_FILE = "leaders_score_history.json"
MIN_QUOTE_COVERAGE = float(os.environ.get("MIN_QUOTE_COVERAGE", "0.97"))
QUOTE_CHUNK = 120
DOWNLOAD_CHUNK = 160


def now_utc_str():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def et_now():
    return datetime.now(timezone.utc).astimezone(ET_ZONE)


def current_week_id():
    d = et_now().date()
    iso = d.isocalendar()
    return f"{iso.year}-W{iso.week:02d}", d.isoformat()


def in_market_hours():
    now = et_now()
    if now.weekday() >= 5 or is_us_market_holiday(now.date().isoformat()):
        return False
    minute = now.hour * 60 + now.minute
    return 570 <= minute <= 961


def finite_num(v):
    try:
        f = float(v)
        if math.isfinite(f) and f > 0:
            return f
    except Exception:
        pass
    return None


def normalize_symbol(sym):
    return str(sym or "").strip().upper().replace(".", "-")


def quote_get(q, *keys):
    for k in keys:
        if k in q:
            v = finite_num(q.get(k))
            if v is not None:
                return v
    return None


def fetch_quotes_yahoo_endpoint(tickers):
    out = {}
    if not tickers:
        return out
    if _session is None and requests is None:
        return out

    client = _session if _session is not None else requests
    url = "https://query1.finance.yahoo.com/v7/finance/quote"
    headers = {"User-Agent": "Mozilla/5.0"}
    for i in range(0, len(tickers), QUOTE_CHUNK):
        batch = tickers[i:i + QUOTE_CHUNK]
        try:
            resp = client.get(url, params={"symbols": ",".join(batch)}, headers=headers, timeout=20)
            if getattr(resp, "status_code", 0) != 200:
                continue
            payload = resp.json()
            rows = payload.get("quoteResponse", {}).get("result", [])
            for q in rows:
                tk = normalize_symbol(q.get("symbol"))
                last = quote_get(q, "regularMarketPrice", "postMarketPrice", "preMarketPrice")
                prev = quote_get(q, "regularMarketPreviousClose", "regularMarketPreviousCloseRaw")
                vol = quote_get(q, "regularMarketVolume")
                if last is not None:
                    out[tk] = {"last": last, "prev": prev, "volume": vol, "source": "quote"}
        except Exception:
            pass
        time.sleep(0.2)
    return out


def flatten_single_download(df):
    if hasattr(df.columns, "names") and df.columns.names and "Ticker" in df.columns.names:
        df = df.droplevel("Ticker", axis=1)
    elif hasattr(df.columns, "nlevels") and df.columns.nlevels == 2:
        df = df.droplevel(1, axis=1)
    return df


def extract_download_ticker(df, tk):
    if df is None or df.empty:
        return None
    cols = df.columns
    if hasattr(cols, "names") and cols.names and "Ticker" in cols.names:
        try:
            return df.xs(tk, axis=1, level="Ticker")
        except Exception:
            return None
    if hasattr(cols, "nlevels") and cols.nlevels == 2:
        try:
            return df.xs(tk, axis=1, level=1)
        except Exception:
            return None
    try:
        return df[tk]
    except Exception:
        return None


def fetch_quotes_yfinance_download(tickers):
    out = {}
    if not tickers:
        return out
    for i in range(0, len(tickers), DOWNLOAD_CHUNK):
        batch = tickers[i:i + DOWNLOAD_CHUNK]
        try:
            df = yf.download(
                batch,
                period="5d",
                interval="1d",
                group_by="ticker",
                auto_adjust=False,
                session=_session,
                threads=True,
                progress=False,
            )
            if df is None or df.empty:
                continue
            if len(batch) == 1:
                sub = flatten_single_download(df.copy())
                closes = sub.get("Close")
                if closes is not None:
                    closes = closes.dropna()
                    if len(closes) >= 1:
                        prev = float(closes.iloc[-2]) if len(closes) >= 2 else None
                        out[batch[0]] = {"last": float(closes.iloc[-1]), "prev": prev, "source": "download"}
            else:
                for tk in batch:
                    sub = extract_download_ticker(df, tk)
                    if sub is None or sub.empty or "Close" not in sub:
                        continue
                    closes = sub["Close"].dropna()
                    if len(closes) >= 1:
                        prev = float(closes.iloc[-2]) if len(closes) >= 2 else None
                        out[tk] = {"last": float(closes.iloc[-1]), "prev": prev, "source": "download"}
        except Exception:
            pass
        time.sleep(0.4)
    return out


def fetch_fast_info_one(ticker):
    try:
        ti = yf.Ticker(ticker, session=_session)
        fi = ti.fast_info
        last = quote_get(fi, "lastPrice", "last_price")
        prev = quote_get(fi, "previousClose", "previous_close")
        if last is not None:
            return ticker, {"last": last, "prev": prev, "source": "fast_info"}
    except Exception:
        pass
    return ticker, None


def fetch_quotes_fast_info(tickers, max_workers=32):
    out = {}
    if not tickers:
        return out
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futs = {ex.submit(fetch_fast_info_one, t): t for t in tickers}
        for fut in as_completed(futs):
            try:
                tk, q = fut.result()
                if q:
                    out[tk] = q
            except Exception:
                pass
    return out


def fetch_quotes(tickers):
    ordered = sorted(set(tickers))
    quotes = fetch_quotes_yahoo_endpoint(ordered)
    missing = [t for t in ordered if t not in quotes]
    print(f"  Quote endpoint: {len(quotes)}/{len(ordered)}")

    if missing:
        dl = fetch_quotes_yfinance_download(missing)
        quotes.update(dl)
        missing = [t for t in ordered if t not in quotes]
        print(f"  yfinance download fallback: +{len(dl)} ({len(missing)} missing)")

    if missing:
        fi = fetch_quotes_fast_info(missing)
        quotes.update(fi)
        missing = [t for t in ordered if t not in quotes]
        print(f"  fast_info fallback: +{len(fi)} ({len(missing)} missing)")

    return quotes, missing


def valid_quote(ticker, quote, old_price):
    if not quote:
        return None
    last = finite_num(quote.get("last"))
    if last is None:
        return None
    if old_price:
        old = finite_num(old_price)
        if old and (last > old * 1.8 or last < old * 0.2):
            print(f"  [reject] {ticker}: live ${last:.2f} implausible vs baseline ${old:.2f}")
            return None
    prev = finite_num(quote.get("prev"))
    if prev:
        ch = (last / prev - 1) * 100
        if ch > 90 or ch < -90:
            print(f"  [reject] {ticker}: 1D change {ch:.1f}% implausible")
            return None
    return {"last": last, "prev": prev, "source": quote.get("source", "")}


WEEKLY_WEIGHTS = [0.12, 0.11, 0.10, 0.09, 0.08, 0.08, 0.08, 0.08, 0.07, 0.07, 0.06, 0.06]


def recency_weighted(window):
    wts = WEEKLY_WEIGHTS[:len(window)]
    wts_rev = list(reversed(wts))
    total_w = sum(wts_rev)
    if total_w == 0:
        return 0.0
    return sum(w * d for w, d in zip(wts_rev, window)) / total_w


def weekly_series_from_deltas(deltas):
    sma_series = []
    for i in range(MA_LENGTH_W - 1, len(deltas)):
        window = deltas[i - MA_LENGTH_W + 1:i + 1]
        sma_series.append(round(recency_weighted(window), 4))
    return sma_series


def streaks(series):
    if not series:
        return 0, 0
    adv = 0
    for j in range(len(series) - 1, 0, -1):
        if series[j] > series[j - 1]:
            adv += 1
        else:
            break
    dec = 0
    for j in range(len(series) - 1, 0, -1):
        if series[j] < series[j - 1]:
            dec += 1
        else:
            break
    return dec, adv


def compute_intraday_weekly(base, live_price, spy_live, week_id):
    try:
        deltas = [float(x) for x in base.get("_w_deltas", []) if x is not None]
        same_week = base.get("_w_week") == week_id
        stock_prev = base.get("_w_stock_prev") if same_week else base.get("_w_stock_last")
        spy_prev = base.get("_w_spy_prev") if same_week else base.get("_w_spy_last")
        stock_atr = finite_num(base.get("_w_stock_atr"))
        spy_atr = finite_num(base.get("_w_spy_atr"))
        stock_prev = finite_num(stock_prev)
        spy_prev = finite_num(spy_prev)
        if not deltas or not stock_prev or not spy_prev or not stock_atr or not spy_atr or not spy_live:
            return None

        stock_chg = live_price - stock_prev
        spy_chg = spy_live - spy_prev
        spy_pi = spy_chg / spy_atr
        expected = spy_pi * stock_atr
        latest_delta = (stock_chg - expected) / stock_atr

        if same_week and deltas:
            deltas[-1] = latest_delta
        else:
            deltas.append(latest_delta)
            deltas = deltas[-LOOKBACK_W:]

        series = weekly_series_from_deltas(deltas)
        if not series:
            return None
        dec, adv = streaks(series)
        return {
            "w_fr": round(series[-1], 4),
            "w_vs": series,
            "w_rf": dec,
            "w_ra": adv,
            "_intraday_deltas": deltas,
        }
    except Exception:
        return None


def live_crash_penalty(base, price):
    high_52w = finite_num(base.get("_hi52"))
    atr = finite_num(base.get("_atr"))
    price = finite_num(price)
    if not high_52w or not atr or not price:
        return bool(base.get("w_pen_crash5"))
    if price >= high_52w:
        return False
    adr_pct = (atr / price) * 100
    if adr_pct > 20:
        threshold = 2.0
    elif adr_pct > 10:
        threshold = 3.0
    elif adr_pct > 4:
        threshold = 4.0
    else:
        threshold = 5.0
    return (high_52w - price) > threshold * atr


def update_change_fields(entry, base, quote):
    live = quote["last"]
    prev = quote.get("prev") or base.get("_pc") or entry.get("p")
    entry["p"] = round(live, 2)
    if prev:
        entry["ch"] = round((live / prev - 1) * 100, 2)
    for key, out_key in (("_5b", "c5"), ("_20b", "c20"), ("_yb", "ytd")):
        b = finite_num(base.get(key))
        if b:
            entry[out_key] = round((live / b - 1) * 100, 2)

    atr = finite_num(base.get("_atr"))
    sma50 = finite_num(base.get("_sma50"))
    if atr and sma50:
        gain_pct = (live - sma50) / sma50 * 100
        atr_pct = atr / live * 100
        if atr_pct > 0:
            entry["ax"] = round((gain_pct / atr_pct) * 100)

    ma_flags = 0
    for bit, key in ((1, "_sma10"), (2, "_sma20"), (4, "_sma50"), (8, "_sma200")):
        sma = finite_num(base.get(key))
        if sma and live > sma:
            ma_flags |= bit
    entry["ma"] = ma_flags


def next_ema(prev_ema, price, period):
    mult = 2.0 / (period + 1.0)
    return (price - prev_ema) * mult + prev_ema


def update_intraday_setup_flags(entry, base, live_price):
    ema9_prev = finite_num(base.get("_setup_ema9"))
    ema21_prev = finite_num(base.get("_setup_ema21"))
    adr = finite_num(base.get("_setup_adr"))
    live = finite_num(live_price)
    if not ema9_prev or not ema21_prev or not adr or not live:
        return False

    ema9_live = next_ema(ema9_prev, live, 9)
    ema21_live = next_ema(ema21_prev, live, 21)
    coiled = abs(ema9_live - ema21_live) < (0.5 * adr)

    flags = int(entry.get("sf") or 0)
    if coiled:
        flags |= SETUP_COILED_FLAG
    else:
        flags &= ~SETUP_COILED_FLAG
    entry["sf"] = flags
    return True


def rerank(entries, baselines, quotes, spy_quote):
    week_id, _ = current_week_id()
    spy_live = spy_quote["last"]
    updated = 0
    stale = []
    setup_updated = 0

    for entry in entries:
        tk = entry.get("t")
        base = baselines.get(tk, {})
        quote = valid_quote(tk, quotes.get(tk), entry.get("p"))
        if quote:
            update_change_fields(entry, base, quote)
            if update_intraday_setup_flags(entry, base, quote["last"]):
                setup_updated += 1
            updated += 1
        else:
            stale.append(tk)

        live_price = finite_num(entry.get("p"))
        if not live_price:
            continue
        w = compute_intraday_weekly(base, live_price, spy_live, week_id)
        if w:
            entry["w_fr"] = w["w_fr"]
            entry["w_vs"] = w["w_vs"]
            entry["w_rf"] = w["w_rf"]
            entry["w_ra"] = w["w_ra"]
            entry["_intraday_deltas"] = w["_intraday_deltas"]
        entry["_live_crash5"] = live_crash_penalty(base, live_price)

    all_w = [e.get("w_fr") for e in entries if e.get("w_fr") is not None]
    for entry in entries:
        if entry.get("w_fr") is None or len(all_w) <= 1:
            entry["_w_rs_raw"] = None
            entry["w_rs"] = None
            continue
        raw = percentrank_inc(all_w, entry["w_fr"]) * 100
        base = baselines.get(entry.get("t"), {})
        score = raw
        if base.get("w_pen_engulf"):
            score -= 2.0
        if entry.get("_live_crash5"):
            score *= 0.70
        final = max(0.0, min(100.0, score))
        entry["w_rs"] = round(final)
        entry["_w_rs_raw"] = final

    rankable = [e for e in entries if e.get("_w_rs_raw") is not None]
    unrankable = [e for e in entries if e.get("_w_rs_raw") is None]
    ranked = sorted(
        rankable,
        key=lambda x: (
            x["_w_rs_raw"],
            x.get("w_fr") if x.get("w_fr") is not None else -999,
            x.get("c5") if x.get("c5") is not None else -999,
        ),
        reverse=True,
    )
    for i, entry in enumerate(ranked, start=1):
        entry["w_rk"] = i
    for entry in unrankable:
        entry["w_rk"] = None

    for entry in entries:
        for k in ("_w_rs_raw", "_live_crash5", "_intraday_deltas"):
            if k in entry:
                del entry[k]

    if setup_updated:
        print(f"  Intraday setup flags: refreshed 9/21 EMA coiled for {setup_updated}/{len(entries)} entries")

    return updated, stale


def update_score_history(entries):
    history = {"dates": [], "d": {}}
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE) as f:
                history = json.load(f)
        except Exception:
            history = {"dates": [], "d": {}}

    dates = history.get("dates", [])
    scores = history.get("d", {})
    for item in scores.values():
        if isinstance(item, dict):
            item.pop("ws", None)
    today = et_now().date().isoformat()
    if not dates or dates[-1] != today:
        dates.append(today)
        is_new_day = True
    else:
        is_new_day = False

    by_ticker = {e.get("t"): e for e in entries if e.get("t")}
    for entry in entries:
        tk = entry.get("t")
        if not tk:
            continue
        scores.setdefault(tk, {})
        scores[tk].setdefault("wr", [])
        while len(scores[tk]["wr"]) < len(dates) - 1:
            scores[tk]["wr"].append(None)
        if len(scores[tk]["wr"]) == len(dates):
            scores[tk]["wr"][-1] = entry.get("w_rk")
        else:
            scores[tk]["wr"].append(entry.get("w_rk"))

    if len(dates) > MAX_HISTORY_DAYS:
        trim = len(dates) - MAX_HISTORY_DAYS
        dates = dates[trim:]
        for tk in scores:
            if "wr" in scores[tk] and len(scores[tk]["wr"]) > MAX_HISTORY_DAYS:
                scores[tk]["wr"] = scores[tk]["wr"][trim:]

    def in_top40(rk):
        return rk is not None and rk <= 40

    for tk, item in list(scores.items()):
        wr = item.get("wr", [])
        today_rk = wr[-1] if wr else None
        yest_rk = wr[-2] if len(wr) >= 2 else None
        entry = by_ticker.get(tk)
        today_in = in_top40(today_rk)
        yest_in = in_top40(yest_rk)
        if today_in and not yest_in:
            if entry and entry.get("p") is not None:
                item["te"] = {"d": today, "p": entry["p"]}
        elif not today_in:
            item.pop("te", None)
        elif "te" not in item and entry and entry.get("p") is not None:
            start_idx = len(wr) - 1
            for i in range(len(wr) - 2, -1, -1):
                if in_top40(wr[i]):
                    start_idx = i
                else:
                    break
            item["te"] = {"d": dates[start_idx] if start_idx < len(dates) else today, "p": entry["p"]}

    with open(HISTORY_FILE, "w") as f:
        json.dump({"dates": dates, "d": scores}, f, separators=(",", ":"))
    return is_new_day


def main():
    print("=" * 60)
    print("Liquid Leaders - Fast Intraday Reranker")
    print("=" * 60)

    if not os.environ.get("FORCE_INTRADAY") and not in_market_hours():
        print("[skip] Outside regular market hours; no intraday update written.")
        return

    if not os.path.exists(LEADERS_FILE):
        print(f"ERROR: {LEADERS_FILE} not found")
        sys.exit(1)
    if not os.path.exists(INTRADAY_BASELINES_FILE):
        print(f"ERROR: {INTRADAY_BASELINES_FILE} not found; run fetch_leaders.py once first")
        sys.exit(2)

    with open(LEADERS_FILE) as f:
        data = json.load(f)
    with open(INTRADAY_BASELINES_FILE) as f:
        baseline_payload = json.load(f)

    entries = data.get("e", [])
    baselines = baseline_payload.get("d", {})
    tickers = [e.get("t") for e in entries if e.get("t")]
    quote_tickers = tickers + ["SPY"]

    print(f"Fetching current quotes for {len(tickers)} stocks + SPY...")
    t0 = time.time()
    quotes, missing = fetch_quotes(quote_tickers)
    spy_quote = valid_quote("SPY", quotes.get("SPY"), None)
    if not spy_quote:
        print("ERROR: SPY quote unavailable; refusing to publish intraday ranks")
        sys.exit(1)

    missing_stocks = [t for t in tickers if t not in quotes]
    coverage = (len(tickers) - len(missing_stocks)) / len(tickers) if tickers else 0
    print(f"Quote coverage: {coverage:.1%} ({len(tickers)-len(missing_stocks)}/{len(tickers)}) in {time.time()-t0:.1f}s")
    if coverage < MIN_QUOTE_COVERAGE:
        print(f"ERROR: quote coverage below {MIN_QUOTE_COVERAGE:.0%}; refusing to publish")
        print(f"Missing sample: {missing_stocks[:40]}")
        sys.exit(1)

    updated, stale = rerank(entries, baselines, quotes, spy_quote)
    valid_coverage = updated / len(tickers) if tickers else 0
    if valid_coverage < MIN_QUOTE_COVERAGE:
        print(f"ERROR: valid quote coverage below {MIN_QUOTE_COVERAGE:.0%}; refusing to publish")
        print(f"Stale sample: {stale[:40]}")
        sys.exit(1)

    history_new_day = update_score_history(entries)

    meta = data.setdefault("meta", {})
    meta["updated"] = now_utc_str()
    meta["count"] = len(entries)
    meta["universe"] = len(entries)
    meta["rank_mode"] = "intraday"
    meta["quote_coverage"] = round(valid_coverage, 4)
    meta["quotes_updated"] = updated
    meta["quotes_stale"] = len(stale)
    meta["spy_price"] = round(spy_quote["last"], 2)
    if spy_quote.get("prev"):
        meta["spy_change"] = round((spy_quote["last"] / spy_quote["prev"] - 1) * 100, 2)

    with open(LEADERS_FILE, "w") as f:
        json.dump(data, f, separators=(",", ":"))

    print(f"Output: {LEADERS_FILE} ({len(entries)} stocks, {updated} live quotes, {len(stale)} stale)")
    print(f"  {HISTORY_FILE} ({'new day' if history_new_day else 'same-day refresh'})")


if __name__ == "__main__":
    main()
